### ISSUE TITLE
Jump in levels of mastery

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/ddat-pathway-product-service-manager#2]
In the [Levels of Mastery Overview](https://github.com/alphagov/ddat-pathway-product-service-manager/blob/master/product-manager/levels-of-mastery-overview.adoc) there is a jump from `Working` to `Expert` in the 'Working with Agility' row between PM and SPM. This is the only technical capability that doesn't have a stage for `Practitioner`.

Is there a reason for that?

**Comment by rossferg** [comment]
The thinking was/is that you can start in PM with Working but you need to be Expert to start in SPM.
